### ISSUE TITLE
Could not resolve library path for .../vscode-codeql-starter/codeql-custom-queries-java

### ISSUE THREAD

**Issue by aabashkin** [github/vscode-codeql-starter#144]
1. Created database from test code
2. Checked out the git repo
3. Opened example.ql
4. Ran query through VS Code extension

Error: Could not resolve library path for .../vscode-codeql-starter/codeql-custom-queries-java

**Comment by MathiasVP** [comment]
Hi @aabashkin,

I'm unable to reproduce your issue when I set up the VSCode starter project as described in the [readme](https://github.com/github/vscode-codeql-starter/blob/main/README.md)'s `#instructions` section. Did you follow that step-by-step guide to set up your installation? If not, I suggest you do that.

If you did follow that step-by-step guide: Can you upload the full output from the `CodeQL Query Server` window from VSCode?
